apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "minio.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "minio.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  secretName: {{ include "minio.fullname" . }}-cert
  # privateKey:
  #   algorithm: ECDSA
  #   size: 256
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "minio.fullname" . }}-ca
  commonName: localhost
  dnsNames:
  - {{ include "minio.fullname" . }}
  - {{ include "minio.fullname" . }}.{{ .Release.Namespace }}.svc
