apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  type: NodePort
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  # sessionAffinity: ClientIP
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}

# {{ .Values.service.port }}
